---
title: "Get Centroids"
author: "CEID Disease Mapping Working Group"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libLoad, message = F}
library(tidyverse)
library(magrittr)
library(sf)
library(measurements)
library(tmap)
library(spData)
library(here)
```

```{r getData}
#set correct path and uncomment next line to get ecoregions
ecoReg <- sf::st_read("/Users/danielsuh/Desktop/Terrestrial_Ecoregions/Terrestrial_Ecoregions.shp")
ecoReg <- sf::st_transform(ecoReg, st_crs(world))

sf_use_s2(FALSE) #whether to use spherical geometry
```

```{r getCentroids}
centroids <- st_centroid(ecoReg) #get centroids
```

```{r distanceMatrix}
dist_mat <- as_tibble(st_distance(centroids, centroids)) #make distance matrix between all centroids
dist_mat <- drop_units(dist_mat)
rownames(dist_mat) <- centroids$ECO_NAME #rename rownames with something. here I just used ECO_NAME
colnames(dist_mat) <- centroids$ECO_NAME #same thing with columns
```

```{r}
centroid_distances <- dist_mat %>% 
  rownames_to_column(., var = "ECO_NAME") %>% 
  pivot_longer(cols = 2:815,
               names_to = "ECO_NAME_2",
               values_to = "meters")

saveRDS(centroid_distances, file = here("data", "processed_data", "centroid_dist.rds"))
```



Centroids will sometimes fall outside of a polygon depending on the shape of the polygon. st_point_on_surface() always chooses a point that is on the polygon.
```{r centroidOnSurface}
pts_on_surface <- st_point_on_surface(ecoReg)
dist_mat_on_surface <- as_tibble(st_distance(pts_on_surface, pts_on_surface))
rownames(dist_mat_on_surface) <- pts_on_surface$ECO_CODE
colnames(dist_mat_on_surface) <- pts_on_surface$ECO_CODE
```


