---
title: "Assign x,y to ecoregions using sf toolkit"
author: "CEID Disease Mapping Working Group"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r libLoad, message = F}
library(tidyverse)
library(magrittr)
library(sf)
library(measurements)
library(tmap)
library(spData)
library(here)
```

```{r getData}
#set correct path and uncomment next line to get ecoregions
#ecoReg <- sf::st_read("/Users/dcsuh/Desktop/Terrestrial_Ecoregions/Terrestrial_Ecoregions.shp")
q <- readr::read_tsv(here("data/MalAvi_9131431.tsv"))
ecoReg <- sf::st_transform(ecoReg, st_crs(world))
```

```{r manip}
#reduce to records with lat/long
q %<>% drop_na(coordinates)

#turn coords column to lat long
q %<>% mutate(lat = stringr::str_replace_all(coordinates,"\\,.*"," "),
              lon = stringr::str_replace_all(coordinates,".*,",""))

q %<>% mutate(lat = stringr::str_replace_all(lat," ",""),
              lon = stringr::str_replace_all(lon," ",""))
q %<>% mutate(lat = stringr::str_replace_all(lat,"°"," "),
              lon = stringr::str_replace_all(lon,"°"," "))
q %<>% mutate(lat = stringr::str_replace_all(lat,"º"," "),
              lon = stringr::str_replace_all(lon,"º"," "))
q %<>% mutate(lat = stringr::str_replace_all(lat,"'",""),
              lon = stringr::str_replace_all(lon,"'",""))
q %<>% mutate(lat = stringr::str_replace_all(lat,"`",""),
              lon = stringr::str_replace_all(lon,"`",""))
q %<>% mutate(lat = stringr::str_replace_all(lat,"´",""),
              lon = stringr::str_replace_all(lon,"´",""))
q %<>% mutate(lat = stringr::str_replace_all(lat,"′",""),
              lon = stringr::str_replace_all(lon,"′",""))
q %<>% mutate(lat = stringr::str_replace_all(lat,"’",""),
              lon = stringr::str_replace_all(lon,"’",""))

q %<>% mutate(lat = measurements::conv_unit(lat,from='deg_dec_min',to='dec_deg'),
              lon = measurements::conv_unit(lon,from='deg_dec_min',to='dec_deg'))


q %<>% mutate(lat=as.numeric(lat),
              lon=as.numeric(lon))
```



```{r make sf}
#q %<>% dplyr::filter(`#no`!=2642) #wrong coords
q %<>% dplyr::filter(lat>-300) #remove weird points with very low lat

pnts_sf <- st_as_sf(q, coords = c('lon', 'lat'), crs = st_crs(world)) #make into sf object
sf_use_s2(F) #spherical geometry OFF; not sure why we need to do this
```

```{r basic map}
tm_shape(pnts_sf) + tm_dots() + tm_shape(world) + tm_borders() #simple map
```

```{r assign regions}
#make new sf with columns indicating which ecoregion each point is in
pnts <- pnts_sf %>% mutate(
  intersection=as.integer(st_intersects(geometry, ecoReg)),
  ecoRegion=if_else(is.na(intersection),'',ecoReg$ECO_NAME[intersection]),
  mht=if_else(is.na(intersection),'',ecoReg$WWF_MHTNAM[intersection]),
) 
```

```{r color points by ecoregion}
tm_shape(world) + tm_borders() + 
  tm_shape(pnts) + tm_dots(col = as.factor("ecoRegion"), size = 0.1, legend.show = F) + 
  tmap_options(max.categories = n_distinct(pnts$ecoRegion))
```

```{r missing points}
#save map object of missing points for ecoregion
missing_pts_tm <- pnts %>% filter(ecoRegion == "") %>% tm_shape(.) + tm_dots() #NA's were previously labeled as "" (i.e. nothing)
tm_shape(world) + tm_borders() + missing_pts_tm
```

```{r color points by mht}
tm_shape(world) + tm_borders() + 
  tm_shape(pnts) + tm_dots(col = as.factor("mht"), size = 0.1, legend.show = F) + 
  tmap_options(max.categories = n_distinct(pnts$mht))
```

```{r save RDS}
#save RDS of malavi points data with assigned ecoregions
#uncomment next line if you need to save this again
#saveRDS(pnts, file = here("data","processed_data","points.rds"))
```

