---
title: "workshop"
output: html_document
date: "2022-10-31"
---

```{r, message = F}
library(tidyverse)
library(magrittr)
library(here)
library(sf)
library(measurements)
library(tmap)
library(spData)
library(tmaptools)
```


```{r, message = F}
host <- read_tsv(here("data/MalAvi_9131431.tsv"))
vec <- read_tsv(here("data/MalAvi_8718204.tsv"))
```


```{r}
world <- read_sf(system.file("shapes/world.gpkg", package = "spData"))
world_crs <- st_crs(world)
world_bbox <- st_bbox(world)
```


```{r}
host_sf <- host %>% mutate(lat = gsub("\\,.*", " ", host$coordinates),
                           lon = gsub(".*,", "",host$coordinates))

host_sf %<>% drop_na(coordinates)

host_sf %<>% mutate(lat = gsub(" ", "", host_sf$lat),
                    lon = gsub(" ", "", host_sf$lon))

# host_sf %<>% mutate(lat = gsub("°", " ", host_sf$lat),
#                     lon = gsub("°", " ", host_sf$lon))
# 
# host_sf %<>% mutate(lat = gsub(".", " ", host_sf$lat, fixed = TRUE),
#                     lon = gsub(".", " ", host_sf$lon, fixed = TRUE))

host_sf %<>% mutate(lat = gsub("'", "", host_sf$lat),
                    lon = gsub("'", "", host_sf$lon))

host_sf %<>% mutate(lat = gsub("`", "", host_sf$lat),
                    lon = gsub("`", "", host_sf$lon))

host_sf %<>% mutate(lat = gsub("´", "", host_sf$lat),
                    lon = gsub("´", "", host_sf$lon))

host_sf %<>% mutate(lat = gsub("′", "", host_sf$lat),
                    lon = gsub("′", "", host_sf$lon))

host_sf %<>% mutate(lat = gsub("’", "", host_sf$lat),
                    lon = gsub("’", "", host_sf$lon))

host_sf %<>% mutate(lat = gsub("0+$", "", host_sf$lat),
                    lon = gsub("0+$", "", host_sf$lon))

host_sf %<>% mutate(lat = gsub("^0+", "", host_sf$lat),
                    lon = gsub("^0+", "", host_sf$lon))


## need to do this MANUALLY

host_sf %<>% mutate(lat_deg = as.numeric(gsub("°.*", "", host_sf$lat)),
                    lon_deg = as.numeric(gsub("°.*.", "", host_sf$lon)))

host_sf %<>% mutate(lat_min = gsub(".*°", "", host_sf$lat),
                    lon_min = gsub(".*°", "", host_sf$lon))

host_sf %<>% mutate(lat_min = as.numeric(gsub("[.].*", "", host_sf$lat_min)),
                    lon_min = as.numeric(gsub("[.].*", "", host_sf$lon_min)))

host_sf %<>% mutate(lat_sec = gsub(".*°", "", host_sf$lat),
                    lon_sec = gsub(".*°", "", host_sf$lon))

host_sf %<>% mutate(lat_sec = as.numeric(gsub(".*[.]", "", host_sf$lat_sec)),
                    lon_sec = as.numeric(gsub(".*[.]", "", host_sf$lon_sec)))

host_sf %<>% mutate(lat_sec = replace_na(lat_sec, 0),
                    lon_sec = replace_na(lon_sec, 0))

#still some NA's due to zeroes in between non-zero characters

host_sf %<>% filter(!is.na(lat_sec) && !is.na(lon_sec)) %>% mutate(lat_dd = lat_deg + (lat_min/60) + (lat_sec/3600),
                                                                   lon_dd = lon_deg + (lon_min/60) + (lon_sec/3600))

# host_sf %<>% mutate(lat_dd = as.numeric(measurements::conv_unit(host_sf$lat, from = 'deg_dec_min', to = 'dec_deg')),
#                     lon_dd = as.numeric(measurements::conv_unit(host_sf$lon, from = 'deg_dec_min', to = 'dec_deg')))

host_sf %<>% drop_na(lat_dd)
host_sf %<>% drop_na(lon_dd)

#host_sf %<>% filter(lat_dd > -180)

host_sf <- st_as_sf(host_sf, coords = c("lon_dd", "lat_dd"), crs = world_crs, remove = F)
```


```{r, message = F}
host_eur <- host_sf %>% filter(continent == c("Europe"))
host_afr <- host_sf %>% filter(continent == c("Africa"))
host_asia <- host_sf %>% filter(continent == c("Asia"))
host_noa <- host_sf %>% filter(continent == c("North America"))
host_oce <- host_sf %>% filter(continent == c("Oceania"))
host_soa <- host_sf %>% filter(continent == c("South America"))
host_usa <- host_sf %>% filter(country == c("United States"))

host_eao <- rbind(host_eur, host_afr)
#vec_eao <- vec %>% filter(country == c("Austria", "Bulgaria", "Cameroon", "Czech Republic", "France", "Germany", "Italy", "Lithuania", "Madagascar", "Portugal", "Russia", "Spain", "Switzerland", "Turkey"))
```

# Summary of data availability

```{r}
plot(host_eao)
tm_shape(host_eao, bbox = world_bbox) + tm_dots()
```



# Preliminary plots/maps

```{r}
border_eur <- world %>% filter(continent == c("Europe"))
border_afr <- world %>% filter(continent == c("Africa"))

border_eao <- rbind(border_eur, border_afr)



no_am <- world %>% filter(subregion %in% c("Caribbean","Northern America","Central America"))

tm_shape(no_am) + tm_borders() + tm_grid() + tm_shape(host_noa) + tm_dots()


```

```{r}
tm_shape(world) + tm_borders()
tm_shape(world) + tm_polygons()
tm_shape(host_afr) + tm_dots()
tm_shape(host_asia) + tm_dots()
tm_shape(host_eur) + tm_dots()
tm_shape(host_noa) + tm_dots()
tm_shape(host_oce) + tm_dots()
tm_shape(host_soa) + tm_dots()

tm_shape(host_sf, bbox = world_bbox) + tm_dots() + tm_shape(world) + tm_borders()
```


```{r}
plot(st_geometry(border_eao))
plot(st_geometry(host_eao), add = T)
```



# EcoRegions

```{r}
ecoregions <- read_sf(here("/Users/dcsuh/Desktop/tm_ecoregions_2017/tm_ecoregions_2017.shp"))
#ecoregions <- ecoregions(class="sf")
ecoregions_2 <- st_transform(ecoregions, world_crs)
sf_use_s2(FALSE)
eco_simple <- st_simplify(ecoregions)
eco_simple <- st_transform(eco_simple, world_crs)
eco_temperate <- eco_simple %>% filter(BIOME_NUM == 5)
```

```{r}
simple_map <- tm_shape(eco_simple) + tm_polygons() + tm_shape(host_sf) + tm_dots()
simple_map
```


```{r}
ecoregions_map <- tm_shape(eco_head) + tm_fill() + tm_shape(host_sf) + tm_dots()
ecoregions_map
```


